import '@/styles/globals.css'
import Header from './components/Header'
import Sidebar from './components/Sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-[100svh] flex'>
          <Sidebar/>
          <div className='flex-1 flex flex-col overflow-hidden'>
            <Header/>
            {children}
          </div>
      </body>
    </html>
  )
}
